---
apiVersion: v1
kind: Service
metadata:
  name: go-app
  labels:
    backstage.io/kubernetes-id: go-clean-code
  annotations:
    backstage.io/kubernetes-id: go-clean-code
spec:
  type: LoadBalancer
  selector:
    app: go-app
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
    backstage.io/kubernetes-id: go-clean-code
  annotations:
    backstage.io/kubernetes-id: go-clean-code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
        backstage.io/kubernetes-id: go-clean-code
      annotations:
        backstage.io/kubernetes-id: go-clean-code
    spec:
      containers:
      - name: go-app
        image: gcr.io/prj-dev-platform-next/backstage:latest
        annotations:
          backstage.io/kubernetes-id: go-clean-code
