---
  name: Build and Push GO Image to Google Cloud Platform
  on:
    workflow_dispatch:
  jobs:
    build-push-gcr:
      name: Build and Push to GCP
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: backstage
        PROJECT_ID: prj-dev-platform-next
      steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: 
          project_id: prj-dev-platform-next
          export_default_credentials: true
          install_components: 'gke-gcloud-auth-plugin'
  
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
  
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-west2-docker.pkg.dev --quiet
  
      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
  
      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push us-west2-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
  
      - name: Deploy to Kubernetes
        run: |
          gcloud container clusters get-credentials go-app --region us-west2
          kubectl apply -f .github/manifests/deployment.yaml --validate=false